sudo: required
services:
  - docker

before_install:
  - docker build -t rama89/react-web-app -f Dockerfile.dev .

script:
  - docker run rama89/react-web-app yarn test a -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'docker-python-web-app'
  env: 'DockerPythonWebApp-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-888746663175'
  bucket_path: 'docker-python-web-app'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
