sudo: required
services:
  - docker

before_install:
  - docker build -t rama89/react-web-app-test -f Dockerfile.dev .

script:
  - docker run rama89/react-web-app-test yarn test a -- --coverage --watchAll=false

deploy:
  # Deploy to Heroku
  - provider: heroku
    app: 'docker-react-web-app'
    on:
      branch: master
    api_key: $HEROKU_AUTH_TOKEN
