sudo: required
services:
  - docker

before_install:
  - docker build -t rama89/react-web-app-test -f Dockerfile.dev .

script:
  - docker run rama89/react-web-app-test yarn test a -- --coverage --watchAll=false

after_success:
  - docker build -t rama89/react-web-app-travis .
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the image to Docker Hub
  - docker push rama89/react-web-app-travis
